#pragma once

/*
 * Apply an EBTRANS.BIN file generated by app/elf_patch/patcher.py.
 *
 * Returns the number of applied entries on success. PSP I/O errors and
 * malformed-file errors are returned as negative values.
 */
int ExternalTranslation_Apply(const char *filename);
